# Generated by Django 3.0.8 on 2020-07-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20200725_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfirmation',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
